name: Build and Deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      - name: "Install Production and Development Dependencies"
        run: "npm install"

      # This section makes as many pages as possible static.
      # If you don't want that, remove it and replace firebase:deploy:functions with firebase:deploy below
      - name: "Export a Static Build"
        run: "npm run export"
      - name: "Deploy Hosting"
        run: "npm run firebase:deploy:hosting"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
